
name: Validate and Promote to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  validate-and-promote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Validate staging model
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        python -c "from validate import validate_model; validate_model(stage='staging', threshold=30000)"

    - name: Promote to production
      run: |
        python src/promote.py
